version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # https://aws.amazon.com/blogs/devops/build-a-continuous-delivery-pipeline-for-your-container-images-with-amazon-ecr-as-source/
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=098017142095.dkr.ecr.us-west-2.amazonaws.com/ecr-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}  
  build:
    commands:
      - echo maven build started on `date`
      - mvn package
      #TODO: TODO : externalize build output file names
      - mv target/spring-petclinic-*.jar spring-petclinic.jar

      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:      
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG      
artifacts:
  files:
    - spring-petclinic.jar
    - .ebextensions/**/*