version: 0.2
# https://aws.amazon.com/blogs/devops/build-a-continuous-delivery-pipeline-for-your-container-images-with-amazon-ecr-as-source/
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html

# https://docs.fossa.com/docs/aws-codebuild
env:
  parameter-store:
    DOCKERHUB_PARAM_USERNAME: /CodeBuild/DOCKERHUB_USERNAME
    DOCKERHUB_PARAM_PASSWORD: /CodeBuild/DOCKERHUB_PASSWORD

phases:
  # install needed only for Docker Build.  Not needed for direct deploy of Jar file
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  # pre_build needed only for Docker Build.  Not needed for direct deploy of Jar file
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - echo AWS_DEFAULT_REGION $AWS_DEFAULT_REGION
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}  

  build:
    commands:
      # Only the following 3 lines for Java assembly and build
      - echo maven build started on `date`
      - env
      - mvn package
      - cp target/spring-petclinic-*.jar ./
      - mv target/spring-petclinic-*.jar spring-petclinic.jar

      # Push commands for ecr-demo

      - echo Building the Docker image...
      # - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker login --username $DOCKERHUB_PARAM_USERNAME --password $DOCKERHUB_PARAM_PASSWORD
      - docker build -t $REPOSITORY_URI/$IMAGE_REPO_NAME:latest .
      - docker tag $REPOSITORY_URI/$IMAGE_REPO_NAME:latest $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:      
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG       

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'

artifacts:
  files:
    - spring-petclinic.jar
    - .ebextensions/**/*
    - imagedefinitions.json